targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
#  my_custom_config:
#    builders:
#      json_serializable:
#        options:
#          # 生成文件的输出目录
#          output: path/to/custom/output/directory
#        generate_for:
#          - lib/my_custom_class.dart